name: deploy-library
description: "Deploy a library"
inputs:
  slack-webhook-url:
    description: "The slack webhook URL to report deployment."
    required: true
runs:
  using: "composite"
  steps:
    - uses: unitasglobal/nio-shared-actions/python-setup@main

    - name: Publish Library
      shell: bash
      run: ./run test pypi-has-version && poetry publish --build -r nio || true

    - name: Get library name and version
      shell: bash
      run: echo "LIBRARY_INFO=$(poetry version)" >> $GITHUB_ENV

    - name: Post to Slack
      uses: fjogeleit/http-request-action@master
      with:
        url: ${{ inputs.slack-webhook-url }}
        method: "POST"
        data: '{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":"\"${{ env.LIBRARY_INFO }}\" has deployed to NIO PyPI"}}]}'
