name: deploy-library
description: "Deploy a library"
inputs:
  python_version:
    description: "The python version to use, in the format '{major}.{minor}'"
    default: "3.9"
    required: false
runs:
  using: "composite"
  steps:
    - uses: unitasglobal/nio-shared-actions/python-setup@main
      with:
        python_version: ${{ inputs.python_version }}

    - name: Publish Library
      shell: bash
      run: ./run test pypi-has-version || poetry publish --build -r nio

    - name: Post Workflow Failed to Slack
      shell: bash
      run: ./run pipeline post-library-released-to-slack
