name: deploy-library
description: "Deploy a library"
runs:
  using: "composite"
  steps:
    - uses: unitasglobal/nio-shared-actions/python-setup@main

    - name: Publish Library
      shell: bash
      run: ./run test pypi-has-version || poetry publish --build -r nio

    - name: Post Workflow Failed to Slack
      shell: bash
      run: ./run pipeline post-library-released-to-slack
