name: static-analysis
description: "Run self check"
inputs:
  python_version:
    description: "The python version to use, in the format '{major}.{minor}'"
    default: "3.9"
    required: false
  version_check:
    description: "Check for library version increment"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Set checkout depth
      shell: bash
      id: checkout-depth
      run: |
        fetch_depth=1
        if [[ ${{ inputs.version_check }} == 'true' ]]; then fetch_depth=0; fi
        echo "::set-output name=fetch_depth::$fetch_depth"

    - uses: unitasglobal/nio-shared-actions/python-setup@main
      with:
        fetch_depth: ${{ steps.checkout-depth.outputs.fetch_depth }}
        python_version: ${{ inputs.python_version }}

    - name: Cache Pre-Commit data
      uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: pre-commit-

    - name: Run Self Check
      shell: bash
      run: ./run test self-check

    - name: ensure main is accessible
      shell: bash
      run: git branch main origin/main >/dev/null 2>&1 || true

    - name: Run Version Check
      if: ${{ inputs.version_check == 'true' }}
      shell: bash
      run: poetry run check-version
