name: static-analysis
description: "Run self check"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: unitasglobal/nio-shared-actions/python-setup@main

    - name: Run Self Check
      shell: bash
      run: ./run test self-check
