name: review-cleanup
description: "Clean up after a review closes"
inputs:
  repo_token:
    description: "Github Token"
    required: true
  python_version:
    description: "The python version to use, in the format '{major}.{minor}'"
    default: "3.9"
    required: false
runs:
  using: "composite"
  steps:
    - uses: unitasglobal/nio-shared-actions/python-setup@main
      with:
        install_node: true
        python_version: ${{ inputs.python_version }}

    - name: Remove Review Stack
      shell: bash
      run: ./run cdk --review ${{ github.event.number }} remove

    - name: Deactivate Review Environment
      uses: bobheadxi/deployments@v1.4.0
      with:
        step: delete-env
        token: ${{ inputs.repo_token }}
        env: review-${{ github.event.number }}
        desc: Environment Pruned
