name: review-cleanup
description: 'Clean up after a review closes'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: unitasglobal/nio-shared-actions/python-setup@main
      with:
        install_node: true

    - name: Deactivate Review Environment
      uses: bobheadxi/deployments@v0.4.3
      with:
        step: deactivate-env
        token: ${{ secrets.GITHUB_TOKEN }}
        env: review-${{ github.event.number }}
        desc: Environment Pruned

    - name: Ensure Only One Remove Run
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Remove Review Stack
      shell: bash
      run: ./run cdk --review ${{ github.event.number }} remove
