name: deploy-review
description: "Deploy a review environment"
inputs:
  repo_token:
    description: "Github Token"
    required: true
  update_iam:
    description: "Update IAM Permissions"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - uses: unitasglobal/nio-shared-actions/python-setup@main

    - name: Check for Docs
      id: check_docs
      uses: andstor/file-existence-action@v1
      with:
        files: "docs/*"

    - name: Check for Deploy Tests
      id: check_deploy_tests
      uses: andstor/file-existence-action@v1
      with:
        files: "tests/deploy_tests/*"

    - name: Get Environment URL
      shell: bash
      run: ./run cdk display --pipeline-key BASE_URL >> $GITHUB_ENV

    - name: Create Review Environment
      if: ${{ env.BASE_URL != '' }}
      uses: bobheadxi/deployments@v1.1.0
      id: deployment
      with:
        step: start
        token: ${{ inputs.repo_token }}
        env: review-${{ github.event.number }}
        ref: ${{ github.head_ref }}
        desc: Review Environment for PR ${{ github.event.number }}

    - name: Ensure Only One Deploy Run
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ inputs.repo_token }}

    - name: Ensure No Dependent Workflows In Progress
      env:
        GITHUB_TOKEN: ${{ inputs.repo_token }}
      shell: bash
      run: ./run pipeline check-dependent-workflows

    - name: Build docs for deploy
      if: ${{ steps.check_docs.outputs.files_exists == 'true' }}
      shell: bash
      run: ./run docs build-user-docs

    - name: Synthesize Default Stacks
      shell: bash
      run: ./run cdk synth

    - name: Update IAM Permissions
      if: ${{ inputs.update_iam == 'true' }}
      shell: bash
      run: ./run data iam-resources

    - name: Deploy Review Stack
      shell: bash
      run: ./run cdk --review ${{ github.event.number }} deploy

    - name: Test Deployed Stack
      if: ${{ steps.check_deploy_tests.files_exists == 'true' }}
      shell: bash
      run: ./run test --review ${{ github.event.number }} deployed

    - name: Update Environment URL
      if: ${{ env.BASE_URL != '' }}
      shell: bash
      run: ./run cdk --review ${{ github.event.number }} display --pipeline-key=BASE_URL >> $GITHUB_ENV

    - name: Update Environment Status
      uses: bobheadxi/deployments@v1.1.0
      if: ${{ env.BASE_URL != '' && always() }}
      with:
        step: finish
        token: ${{ inputs.repo_token }}
        status: ${{ job.status }}
        env: ${{ steps.deployment.outputs.env }}
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
        env_url: ${{ env.BASE_URL }}
