name: deploy-review
description: "Deploy a review environment"
inputs:
  repo_token:
    description: "Github Token"
    required: true
  test:
    description: "Test deployed stack"
    default: "true"
    required: false
  user_docs:
    description: "create user docs"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Create Review Environment
      uses: bobheadxi/deployments@v1.1.0
      id: deployment
      with:
        step: start
        token: ${{ inputs.repo_token }}
        env: review-${{ github.event.number }}
        ref: ${{ github.head_ref }}
        desc: Review Environment for PR ${{ github.event.number }}

    - uses: actions/checkout@v2

    - uses: unitasglobal/nio-shared-actions/python-setup@main

    - name: Ensure Only One Deploy Run
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ inputs.repo_token }}

    - name: Build docs for deploy
      if: ${{ inputs.user_docs == 'true' }}
      shell: bash
      run: |
        ./run docs build-user-docs

    - name: Synthesize Default Stacks
      shell: bash
      run: ./run cdk synth

    - name: Deploy Review Stack
      shell: bash
      run: ./run cdk --review ${{ github.event.number }} deploy

    - name: Test Deployed Stack
      if: ${{ inputs.test == 'true' }}
      shell: bash
      run: ./run test --review ${{ github.event.number }} deployed

    - name: Update Environment URL
      shell: bash
      run: ./run cdk --review ${{ github.event.number }} display --pipeline-key=BASE_URL >> $GITHUB_ENV

    - name: Update Environment Status
      uses: bobheadxi/deployments@v1.1.0
      if: always()
      with:
        step: finish
        token: ${{ inputs.repo_token }}
        status: ${{ job.status }}
        env: ${{ steps.deployment.outputs.env }}
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
        env_url: ${{ env.BASE_URL }}
