name: run-tests
description: "Run pytest tests for a given repo"
inputs:
  codecov-token:
    description: "The token used to upload to CodeCov"
    required: true
  python_version:
    description: "The python version to use, in the format '{major}.{minor}'"
    default: "3.9"
    required: false
runs:
  using: "composite"
  steps:
    - uses: unitasglobal/nio-shared-actions/python-setup@main
      with:
        python_version: ${{ inputs.python_version }}

    - name: Ensure No Dependent Workflows In Progress
      shell: bash
      run: ./run pipeline check-dependent-workflows

    - name: Execute Tests
      shell: bash
      run: ./run test ci

    - uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: PyTest Results
        path: junit*.xml
        reporter: java-junit

    - name: Upload to CodeCov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ inputs.codecov-token }}
        files: ./coverage.xml

    - name: PyTest Results Comment
      uses: MishaKav/pytest-coverage-comment@v1.1.37
      with:
        pytest-xml-coverage-path: ./coverage.xml
