name: run-tests
description: "Run pytest tests for a given repo"
inputs:
  codecov-token:
    description: "The token used to upload to CodeCov"
    required: true
runs:
  using: "composite"
  steps:
    - uses: unitasglobal/nio-shared-actions/python-setup@main

    - name: Ensure No Dependent Workflows In Progress
      shell: bash
      run: ./run pipeline check-dependent-workflows

    - name: Execute Tests
      shell: bash
      run: ./run test ci

    - uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: PyTest Results
        path: junit.xml
        reporter: java-junit

    - name: Upload to CodeCov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ inputs.codecov-token }}
        files: ./coverage.xml

    - name: PyTest Results Comment
      uses: MishaKav/pytest-coverage-comment@v1.1.31
      with:
        junitxml-path: ./junit.xml
        junitxml-title: Test Results
