name: python-setup
description: "Set up Python (and optioanlly node) environment"
inputs:
  install_node:
    description: "Install node"
    required: false
    default: "false"
  fetch_depth:
    description: "Number of commits to fetch. 0 indicates all history for all branches and tags."
    required: false
    default: "1"
  python_version:
    description: "The python version to use, in the format '{major}.{minor}'"
    default: "3.9"
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.fetch_depth }}
        lfs: true

    - name: Set up QEMU
      if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@v2

    - name: use Node.js
      uses: actions/setup-node@v3
      if: ${{ inputs.install_node == 'true' }}
      with:
        node-version: "14"

    - name: Install zip
      if: runner.os == 'Linux'
      uses: montudor/action-zip@v1

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}

    - name: Setup Packer
      uses: hashicorp/setup-packer@main
      with:
        version: "latest"

    - name: Install Poetry
      shell: bash
      run: pip install poetry

    - name: Cache Poetry virtualenv
      uses: actions/cache@v3
      id: poetry-cache
      with:
        path: ~/.cache/pypoetry
        key: poetry-${{ inputs.python_version }}-${{ hashFiles('poetry.lock', 'pyproject.toml') }}
        restore-keys: poetry-${{ inputs.python_version }}-

    - name: Install App and Dependencies
      shell: bash
      run: bash bootstrap.sh
