name: close-pull-request
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
jobs:
  review-cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: unitasglobal/nio-shared-actions/review-cleanup@main
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Post Workflow Failed to Slack
        if: ${{ failure() }}
        shell: bash
        run: ./run pipeline post-workflow-failed-to-slack --workflow-name close-pull-request.yml
