name: deploy-library
on:
  workflow_call:
    inputs:
      python_version:
        description: "The python version to use, in the format '{major}.{minor}'"
        type: string
        default: "3.9"
        required: false
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  DOCKER_BUILDKIT: 1
jobs:
  deploy-library:
    runs-on: ubuntu-latest
    steps:
      - uses: unitasglobal/nio-shared-actions/deploy-library@main
        with:
          python_version: ${{ inputs.python_version }}

      - name: Post Workflow Failed to Slack
        if: ${{ failure() }}
        shell: bash
        run: ./run pipeline post-workflow-failed-to-slack --workflow-name deploy-library.yml
