name: production-deploy
on:
  workflow_call:
    inputs:
      db_port:
        description: "Docker Postgres port"
        type: number
        required: false
        default: 5432
      update_iam:
        description: "Update IAM Permissions"
        type: boolean
        required: false
        default: false
    secrets:
      PROD_AWS_ACCESS_KEY_ID:
        required: true
      PROD_AWS_SECRET_ACCESS_KEY:
        required: true
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  DOCKER_BUILDKIT: 1
  DB_PORT: ${{ inputs.db_port }}
jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: unitasglobal/nio-shared-actions/deploy@main
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          project_name: ${{ inputs.project_name }}
          deploy_flag: "--prod"
          update_iam: ${{ inputs.update_iam }}
          env_name: production
