name: production-deploy
on:
  workflow_call:
    inputs:
      update_iam:
        description: "Update IAM Permissions"
        type: boolean
        required: false
        default: false
      python_version:
        description: "The python version to use, in the format '{major}.{minor}'"
        type: string
        default: "3.9"
        required: false
    secrets:
      PROD_AWS_ACCESS_KEY_ID:
        required: true
      PROD_AWS_SECRET_ACCESS_KEY:
        required: true
      PACKER_GH_TOKEN:
        required: false
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  PACKER_GITHUB_API_TOKEN: ${{ secrets.PACKER_GH_TOKEN }}
  DOCKER_BUILDKIT: 1
jobs:
  deploy-production:
    runs-on: ubuntu-latest
    concurrency: deploy_production
    steps:
      - uses: unitasglobal/nio-shared-actions/deploy@main
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          project_name: ${{ inputs.project_name }}
          deploy_flag: "--prod"
          update_iam: ${{ inputs.update_iam }}
          env_name: production
          python_version: ${{ inputs.python_version }}

      - name: Post Workflow Failed to Slack
        if: ${{ failure() }}
        shell: bash
        run: ./run pipeline post-workflow-failed-to-slack --workflow-name production-deploy.yml
