name: production-deploy
on:
  workflow_call:
    inputs:
      environment_url:
        type: string
        required: true
      db_port:
        description: "Docker Postgres port"
        type: number
        required: false
        default: 5432
      user_docs:
        description: "Create user docs"
        type: boolean
        required: false
        default: true
      test:
        description: "Test deployed stack"
        type: boolean
        required: false
        default: true
    secrets:
      PROD_AWS_ACCESS_KEY_ID:
        required: true
      PROD_AWS_SECRET_ACCESS_KEY:
        required: true
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  DOCKER_BUILDKIT: 1
  DB_PORT: ${{ inputs.db_port }}
jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ inputs.environment_url }}
    steps:
      - uses: unitasglobal/nio-shared-actions/deploy@main
        with:
          user_docs: ${{ inputs.user_docs }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_flag: "--prod"
          test: ${{ inputs.test }}
          env_name: production
          env_url: ${{ inputs.environment_url }}
