name: python-setup
on:
  workflow_call:
    inputs:
      install_node:
        type: boolean
        default: false
        required: false

jobs:
  python_setup:
    name: Set Up python environment
    runs-on: ubuntu-latest
    steps:
      - name: use Node.js
        uses: actions/setup-node@v2
        if: ${{ github.event.inputs.install_node }}
        with:
          node-version: "14"

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        run: pip install poetry

      - name: Cache Poetry virtualenv
        uses: actions/cache@v2
        id: poetry-cache
        with:
          path: ~/.cache/pypoetry
          key: poetry-3.9-${{ hashFiles('poetry.lock', 'pyproject.toml') }}
          restore-keys: poetry-3.9-

      - name: Install App and Dependencies
        run: bash bootstrap.sh
