name: review-requested
on:
  pull_request:
    types: [review_requested]
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
jobs:
  review-requested:
    runs-on: ubuntu-latest
    steps:
      - uses: unitasglobal/nio-shared-actions/python-setup@main

      - name: Get Review Requested Slack Block - Individual Reviewer
        if: ${{ github.event.requested_reviewer }}
        run: ./run pipeline review-requested-slack-blocks --pr_title "${{ github.event.pull_request.title }}" --pr_url "${{ github.event.pull_request.html_url }}" --requestor "${{ github.event.sender.login }}" --reviewer "${{ github.event.requested_reviewer.login }}" >> $GITHUB_ENV

      - name: Get Review Requested Slack Block - Team Reviewer
        if: ${{ github.event.requested_team }}
        run: ./run pipeline review-requested-slack-blocks --pr_title "${{ github.event.pull_request.title }}" --pr_url "${{ github.event.pull_request.html_url }}" --requestor "${{ github.event.sender.login }}" --reviewer "${{ github.event.requested_team.name }}" >> $GITHUB_ENV

      - name: Post to Slack - Review Requested
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          method: "POST"
          data: ${{ env.SLACK_BLOCKS }}
