name: review-requested
on:
  pull_request:
    types: [review_requested]
  workflow_dispatch:

  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
jobs:
  review-requested:
    runs-on: ubuntu-latest
    steps:
      - name: Get URL and Token
        id: endpoint-details
        run: |
          URL=$(aws ssm get-parameter --name ' /nio/development/slack_notifications/url' --with-decryption | jq -r '.Parameter.Value')
          TOKEN=$(aws ssm get-parameter --name ' /nio/development/slack_notifications/token' --with-decryption | jq -r '.Parameter.Value')
          echo "::set-output name=url::$URL"
          echo "::set-output name=token::$TOKEN"

      - uses: actions/setup-python@v2

      - name: Call to send notification
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import urllib.request

            reviewer_name = "the_boogeyman"
            requested_reviewer = "${{ github.event.reviewer_requested }}"
            if requested_reviewer:
              reviewer_name = "${{ github.event.requested_reviewer.login }}"
            requested_team = "${{ github.event.requested_team }}"
            if requested_team:
              reviewer_name = "${{ github.event.requested_team.name }}"

            request = urllib.request.Request("${{ steps.endpoint-details.outputs.url }}", headers={"X-Api-Token": "${{ steps.endpoint-details.outputs.token }}"}, method="POST")

            data_string = "--pr_title '${{ github.event.pull_request.title }}' --pr_url ${{ github.event.pull_request.html_url }} --requestor ${{ github.event.sender.login }} --reviewer " + requested_reviewer
            urllib.request.urlopen(request, data=data_string.encode("utf-8"))
