name: review-requested
on:
  pull_request:
    types: [review_requested]
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
jobs:
  review-requested:
    runs-on: ubuntu-latest
    steps:
      - name: Get URL and Token
        id: endpoint-details
        run: |
          URL=$(aws ssm get-parameter --name ' /nio/development/slack_notifications/url' --with-decryption | jq -r '.Parameter.Value')
          TOKEN=$(aws ssm get-parameter --name ' /nio/development/slack_notifications/token' --with-decryption | jq -r '.Parameter.Value')
          echo "::set-output name=url::$URL"
          echo "::set-output name=token::$TOKEN"

      - uses: actions/setup-python@v3

      - name: Call to send notification
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import json
            import urllib.request

            requested_reviewer = "${{ github.event.requested_reviewer }}"
            requested_team = "${{ github.event.requested_team }}"
            if requested_reviewer:
              reviewer_name = "${{ github.event.requested_reviewer.login }}"
            elif requested_team:
              reviewer_name = "${{ github.event.requested_team.name }}"

            repo = "${{ github.repository }}".split("/")[-1]

            data = {
              "pr_url": "${{ github.event.pull_request.html_url }}",
              "requestor": "${{ github.event.sender.login }}",
              "reviewer": reviewer_name
            }
            request_data = json.dumps(data).encode("utf-8")

            request = urllib.request.Request(
              "${{ steps.endpoint-details.outputs.url }}notify?event_type=review_requested&repo=" + repo,
              headers={
                "X-Api-Token": "${{ steps.endpoint-details.outputs.token }}",
                "Content-Type": "application/json"
              },
              method="POST",
              data=request_data
            )

            urllib.request.urlopen(request)
