name: review-requested
on:
  pull_request:
    types: [review_requested]
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
jobs:
  review-requested:
    runs-on: ubuntu-latest
    steps:
      - name: Set URL and Token Values
        run: |
          URL=$(aws ssm get-parameter --name ' /nio/development/slack_notifications/url' --with-decryption | jq -r '.Parameter.Value')
          echo "API_URL=$URL" >> GITHUB_ENV
          TOKEN=$(aws ssm get-parameter --name ' /nio/development/slack_notifications/token' --with-decryption | jq -r '.Parameter.Value')
          echo "API_TOKEN=$TOKEN" >> GITHUB_ENV


      - name: Post Review Requested to Slack - Individual Reviewer
        if: ${{ github.event.requested_reviewer }}
        run: |
          curl -X POST -H "X-Api-Token: $API_TOKEN" "${API_URL}notify?event_type=review_requested&repo=${{ github.repository }}" -d "--pr_title \'${{ github.event.pull_request.title }}\' --pr_url \'${{ github.event.pulL_request.html_url }}\' --requestor \'${{ github.event.sender.login }}\' --reviewer \'${{ github.event.requested_reviewer.login }}\'"

      - name: Post Review Requested to Slack - Team Reviewer
        if: ${{ github.event.requested_team }}
        run: |
          curl -X POST -H "X-Api-Token: $API_TOKEN" "${API_URL}notify?event_type=review_requested&repo=${{ github.repository }}" -d "--pr_title \'${{ github.event.pull_request.title }}\' --pr_url \'${{ github.event.pulL_request.html_url }}\' --requestor \'${{ github.event.sender.login }}\' --reviewer \'${{ github.event.requested_team.login }}\'"
