name: staging-deploy
on:
  workflow_call:
    inputs:
      environment_url:
        type: string
        required: true
      api_name:
        required: true
        type: string
      db_port:
        required: false
        type: number
        default: 5432
      user_docs:
        required: false
        default: true
        type: boolean
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  DOCKER_BUILDKIT: 1
  DB_PORT: ${{ inputs.db_port }}
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ inputs.environment_url }}
    steps:
      - uses: actions/checkout@v2

      - uses: unitasglobal/nio-shared-actions/deploy@main
        with:
          user_docs: ${{ inputs.user_docs }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Post to Slack
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          method: "POST"
          data: '{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":"${{ inputs.api_name }} has released to Staging"}},{"type":"divider"},{"type":"section","text":{"type":"mrkdwn","text":"Start Production Build"},"accessory":{"type":"button","text":{"type":"plain_text","text":"Open GitHub","emoji":true},"url":"https://github.com/${{ github.repository }}/actions/workflows/production-deploy.yml","action_id":"button-action"}}]}'
