name: staging-deploy
on:
  workflow_call:
    inputs:
      db_port:
        description: "Docker Postgres port"
        type: number
        required: false
        default: 5432
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  DOCKER_BUILDKIT: 1
  DB_PORT: ${{ inputs.db_port }}
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: unitasglobal/nio-shared-actions/deploy@main
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          project_name: ${{ inputs.project_name }}
          env_name: staging

      - name: Manage Production Run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: ./run pipeline manage-production-run
