name: staging-deploy
on:
  workflow_call:
    inputs:
      project_name:
        description: "Project name"
        type: string
        required: true
      db_port:
        description: "Docker Postgres port"
        type: number
        required: false
        default: 5432
      environment_url:
        description: "The URL of the deploy environment"
        type: string
        required: false
        default: ""
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  DOCKER_BUILDKIT: 1
  DB_PORT: ${{ inputs.db_port }}
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ inputs.environment_url }}
    steps:
      - uses: unitasglobal/nio-shared-actions/deploy@main
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          env_name: staging
          env_url: ${{ inputs.environment_url }}

      - name: Manage Production Run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: ./run pipeline manage-production-run
