name: update-coverage
on:
  workflow_call:
    inputs:
      python_version:
        description: "The python version to use, in the format '{major}.{minor}'"
        type: string
        default: "3.9"
        required: false
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      CODECOV_TOKEN:
        required: true
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  DOCKER_BUILDKIT: 1
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: unitasglobal/nio-shared-actions/python-setup@main
        with:
          python_version: ${{ python_version }}

      - name: Ensure No Dependent Workflows In Progress
        shell: bash
        run: ./run pipeline check-dependent-workflows

      - name: Execute Tests
        run: ./run pipeline check-for-test-run --branch-name ${{ github.event.pull_request.head.ref }} && ./run test ci || true

      - name: Upload to CodeCov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml

      - name: Post Workflow Failed to Slack
        if: ${{ failure() }}
        shell: bash
        run: ./run pipeline post-workflow-failed-to-slack --workflow-name update-coverage.yml
