name: update-coverage
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      CODECOV_TOKEN:
        required: true
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  DOCKER_BUILDKIT: 1
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: unitasglobal/nio-shared-actions/python-setup@main

      - name: Execute Tests
        run: ./run test ci

      - name: Upload to CodeCov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml

      - name: Post Workflow Failed to Slack
        if: ${{ failure() }}
        shell: bash
        run: ./run pipeline post-workflow-failed-to-slack --workflow-name deploy-library.yml
