name: update-requirements
on:
  workflow_call:
    inputs:
      python_version:
        description: "The python version to use, in the format '{major}.{minor}'"
        type: string
        default: "3.9"
        required: false
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  DOCKER_BUILDKIT: 1
jobs:
  build-requirements:
    name: Build Requirements ECR Image
    runs-on: ubuntu-latest
    steps:
      - uses: unitasglobal/nio-shared-actions/python-setup@main
        with:
          python_version: ${{ inputs.python_version }}

      - uses: docker/setup-buildx-action
        id: buildx-setup
        with:
          platforms: linux/amd64,linux/arm64
          use: false

      - name: Build and Push Images
        run: ./run docker build-and-push-requirements --multibuilder ${{ steps.buildx-setup.outputs.name }}

      - name: Post Workflow Failed to Slack
        if: ${{ failure() }}
        shell: bash
        run: ./run pipeline post-workflow-failed-to-slack --workflow-name update-requirements.yml
